main: com.cavetale.televator.TelevatorPlugin
name: Televator

version: 0.1
api-version: 1.19

description: Use gold blocks as elevators
author: StarTux
website: https://cavetale.com

depend: [Core]
softdepend: []

permissions:

  televator.televator:
    description: Use televators
    default: op
